codecov:
  notify:
    require_ci_to_pass: yes
  # Codecov will use the default branch for your repository as the "master" copy of the repositories Codecov Yaml. 
  # The default branch, if not otherwise stated, is the master branch. You can change the Codecov default branch in your Yaml
  branch: stable

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
