dist: xenial
sudo: required
language: node_js
node_js: 
  - "10"
  - "9"
  - "stable"
env:
  global:
    - SECRET_TOKEN=k399dkkgklsk
  matrix:
    - ENV=production
    - ENV=testing
branches:
  except:
    - test
cache: 
  yarn: true
  directories: 
    - node_modules
    - ~/.npm
    - ~/.cache
services:
  - mysql
before_install:
  - sudo apt-get update -qq
  - npm i -g yarn
install:
  - yarn install
before_script:
  - pwd
script:
  - yarn cov
after_success:
  - yarn deploy-surge
  - yarn deploy-github
notifications:
  email:
    - loitd@vnptepay.com.vn